### ISSUE TITLE
ERROR in ./src/main.ts Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\Muhammad Zaid\IdeaProjects\angular-seo\src'  @ ./src/main.ts 4:0-74  @ multi ./src/main.ts

### ISSUE THREAD

**Issue by mzaidse** [designcourse/angular-seo#10]
After cloning your repository, I installed dependencies using 'npm install', then I run the command 'npm start' and faced this error. Kindly help me.

```
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\Muhammad Zaid\IdeaProjects\angular-seo\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ang4-seo@0.0.0 prestart: `ng build --prod && ngc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ang4-seo@0.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by SkMamtajuddin** [comment]
Same here 
`ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/skmamtajuddin/workspace/ngseo/FrapSeo/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! ang4-seo@0.0.0 prestart: `ng build --prod && ngc`
npm ERR! Exit status 1
npm ERR!`

**Comment by KrGyan** [comment]
Update angular cli version to 1.2.6 and go ahead !!!

**Comment by luomu172** [comment]
Same here

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v8.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ang4-seo@0.0.0~prestart: ang4-seo@0.0.0
6 verbose lifecycle ang4-seo@0.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle ang4-seo@0.0.0~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\work\code\webStormCode\angular-seo\node_modules\.bin;C:\Program Files (x86)\Common Files\NetSarang;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;%JAVA_HOME%\bin;C:\Program Files\TortoiseSVN\bin;D:\javaEnvironmental\TortoiseGit\bin;D:\javaEnvironmental\apache-maven-3.3.9\bin;C:\Python27\Scripts;D:\HashiCorp\Vagrant\bin;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Roaming\npm;D:\javaTools\qshell
8 verbose lifecycle ang4-seo@0.0.0~prestart: CWD: D:\work\code\webStormCode\angular-seo
9 silly lifecycle ang4-seo@0.0.0~prestart: Args: [ '/d /s /c', 'ng build --prod && ngc' ]
10 silly lifecycle ang4-seo@0.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle ang4-seo@0.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: ang4-seo@0.0.0 prestart: `ng build --prod && ngc`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
12 verbose stack     at emitTwo (events.js:125:13)
12 verbose stack     at EventEmitter.emit (events.js:213:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:125:13)
12 verbose stack     at ChildProcess.emit (events.js:213:7)
12 verbose stack     at maybeClose (internal/child_process.js:927:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13 verbose pkgid ang4-seo@0.0.0
14 verbose cwd D:\work\code\webStormCode\angular-seo
15 verbose Windows_NT 6.1.7601
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
17 verbose node v8.3.0
18 verbose npm  v5.3.0
19 error code ELIFECYCLE
20 error errno 1
21 error ang4-seo@0.0.0 prestart: `ng build --prod && ngc`
21 error Exit status 1
22 error Failed at the ang4-seo@0.0.0 prestart script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by ghost** [comment]
Dear @KrGyan 
I installed `npm install -g @angular/cli`.
But it occurs same error. How can I fix it?

Regards,
Alex

**Comment by SkMamtajuddin** [comment]
Thanks @KrGyan ! its work when update cli to 1.2.6

**Comment by ghost** [comment]
hmm, I updated cli to 1.3.1 But it doesn't still work for me. what' the reason?

**Comment by SkMamtajuddin** [comment]
@alexandra1030  pls use 1.2.6 version and reinstall

**Comment by ghost** [comment]
@SkMamtajuddin oh, yeah, i'll try it. 👍

**Comment by JohannesFerner** [comment]
@SkMamtajuddin @alexandra1030 
I was on 1.5.0 (global); Downgraded to 1.2.6 (global) ...
be aware of 
```
$ ng -version
Your global Angular CLI version (1.2.6) is greater than your local
version (1.0.3). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
```

so do not update via `-g` but update the local version.

Then it worked for me

**Comment by akilmakda** [comment]
run :npm install enhanced-resolve@3.3.0

in your pakage.json file.. in script tag replace this "ng build --prod" with "ng build --env=prod". It will reolve the problem.

**Comment by chozharajan** [comment]
i updated my local angular cli to **1.2.6.**

>  its worked

**Comment by kamalakkanni** [comment]
I am using angular5.Me also getting this issue

**Comment by Mr-Plants** [comment]
@akilmakda thank you!it really work for me
