### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by SkMamtajuddin** [designcourse/angular-seo#12]
When we use window or document , we are getting this error 
`> ang4-seo@0.0.0 start /Users/skmamtajuddin/workspace/ngseo/FrapSeo
> ts-node src/server.ts

/Users/path/masonry-layout/masonry.js:33
}( window, function factory( Outlayer, getSize ) {
   ^
ReferenceError: window is not defined
    at Object.<anonymous> (/path/masonry-layout/masonry.js:33:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/node_modules/angular2-masonry/src/masonry.ts:15:15)
    at Module._compile (module.js:569:30)`

**Comment by hesampour** [comment]
I have the same problem
