### ISSUE TITLE
Lazy module does not working

### ISSUE THREAD

**Issue by GigaGyrfalcon** [designcourse/angular-seo#8]
Is any way to works with lazy modules?

**Comment by jbeckton** [comment]
I was able to clone this and get a lazy loaded module working, can you post your code to a plunker?

**Comment by KrGyan** [comment]
I am getting below error with Lazy Load 

ERROR { Error: Uncaught (in promise): ReferenceError: System is not defined
ReferenceError: System is not defined
    at SystemJsNgModuleLoader.loadFactory (E:\Angular\designcourse\AOT_build_complete\angular-seo\packages\core\src\linker\system_js_ng_module_factory_loader.ts:67:1)
    at SystemJsNgModuleLoader.load (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\@angular\core\bundles\core.umd.js:5666:35)
    at RouterConfigLoader.loadModuleFactory (E:\Angular\designcourse\AOT_build_complete\angular-seo\packages\router\src\router_config_loader.ts:71:1)
    at RouterConfigLoader.load (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\@angular\router\bundles\router.umd.js:3527:52)
    at MergeMapSubscriber.project (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\@angular\router\bundles\router.umd.js:1694:74)
    at MergeMapSubscriber._tryNext (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\rxjs\src\operator\mergeMap.ts:125:21)
    at MergeMapSubscriber._next (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\rxjs\src\operator\mergeMap.ts:115:12)
    at MergeMapSubscriber.Subscriber.next (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\rxjs\src\Subscriber.ts:95:12)
    at ScalarObservable._subscribe (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\rxjs\src\observable\ScalarObservable.ts:51:18)
    at ScalarObservable.Observable._trySubscribe (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\rxjs\src\Observable.ts:216:19)
    at resolvePromise (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\zone.js\dist\zone-node.js:783:31)
    at resolvePromise (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\zone.js\dist\zone-node.js:754:17)
    at E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\zone.js\dist\zone-node.js:831:17
    at ZoneDelegate.invokeTask (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\zone.js\dist\zone-node.js:424:31)
    at Object.onInvokeTask (E:\Angular\designcourse\AOT_build_complete\angular-seo\packages\core\src\zone\ng_zone.ts:288:1)
    at ZoneDelegate.invokeTask (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\zone.js\dist\zone-node.js:423:36)
    at Zone.runTask (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\zone.js\dist\zone-node.js:191:47)
    at drainMicroTaskQueue (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\zone.js\dist\zone-node.js:502:21)
    at Server.ZoneTask.invoke (E:\Angular\designcourse\AOT_build_complete\angular-seo\node_modules\zone.js\dist\zone-node.js:487:48)
